# fly.toml app configuration file generated for biostat-workshop-s23 on 2023-05-10T10:31:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "biostat-workshop-s23"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "lax"

[experimental]
auto_rollback = true

[[services]]
auto_start_machines = true
auto_stop_machines = true
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[services.concurrency]
hard_limit = 20
soft_limit = 15
type = "connections"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = 3000
method = "get"
path = "/healthz"
protocol = "http"
restart_limit = 0
timeout = 1000
[services.http_checks.headers]
Host = "health.check"
